version: '3.8'
services:
  db:
    image: postgres:alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=spots_api
    networks:
      - spots-backend
  test-db:
    image: postgres:alpine
    container_name: postgres_test
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=spots_api_test
    networks:
      - spots-backend

networks:
  spots-backend: