version: '3.8'
services:
  db:
    image: postgres:alpine
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - spots

  test-db:
    image: postgres:alpine
    container_name: test-db
    ports:
      - 5433:5432
    env_file:
      - .env.test
    networks:
      - spots

  api:
    image: rihlan24/backend-spots:latest
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static:/app/static
    ports:
      - 5000:5000
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    networks:
      - spots
    command: ['sh', '-c', 'bun prisma:deploy && bun start']

networks:
  spots:

volumes:
  pgdata:
  static:
